### PR TITLE
Add setup.py script for repo upload.

### PR DESCRIPTION
**Pull request by gxmxni-hashflow**
This script works in conjunction with pyproject.toml to generate packages to publish to PyPI.

Test Plan: uploaded package to PyPI using the following steps:
- python setup.py sdist
- twine check dist/*
- twine upload dist/*

### CODE REVIEW

**Comment by sameer-hashflow** [comment]
My understanding is that `setup.py` is the old way to configure python projects and we should not be using it. The `pyproject.toml` file is the way we build the python project from now on.

https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/

Therefore we should not need a setup.py or requirements-publish, I think everything should go in the pyproject.toml -- 

I already tested publishing this to test pypi without changes, so I think the only change needed here is the version number.

**Comment by gxmxni-hashflow** [comment]
@sameer-hashflow what is your method of publish? Are you able to expand? I believe twine is not set as a requirement in the .txt file, and it's a tool we should have for publishing.

**Comment by sameer-hashflow** [comment]
> @sameer-hashflow what is your method of publish? Are you able to expand? I believe twine is not set as a requirement in the .txt file, and it's a tool we should have for publishing.

The publishing instructions are in the README =) 

```
Building Instructions
---------------------

```sh
python3 -m pip install --upgrade build
python3 -m build
```

Publishing Instructions
-----------------------

```sh
python3 -m pip install --upgrade twine
python3 -m twine upload --repository testpypi dist/*
```

The readme just specifies that you should do pip install twine to get it to publish, so making that a bit nicer with a requirements-publish.txt would help a bit incase we will ever need more than just twine & build to publish. The core issue here is that I don't think we should be using `setup.py` as I think that is the legacy/deprecated way of building wheels.

**Comment by mib-hashflow** [comment]
@gxmxni-hashflow quick check-in: do you need anything else on this PR to continue?

**Comment by sameer-hashflow** [comment]
@gxmxni-hashflow Should we close this PR? I think we don't need to make any changes here just setup process, per the discussion in the ticket.

**Comment by mib-hashflow** [comment]
Closing due to inactivity.

**Pull request closed without merging**
